export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_PAGE = 'TOGGLE_PAGE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const CHANGE_MENU_LABEL = 'CHANGE_MENU_LABEL'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const TOGGLE_LANG = 'TOGGLE_LANG'
